apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: jellyfin.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: jellyfin-tls
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.jellyfin.http.accepted_statuscodes: '["200-299", "302"]'
    kuma.jellyfin.http.name: Jellyfin Media Server
    kuma.jellyfin.http.url: https://jellyfin.gruzin.eu
  labels:
    io.kompose.service: jellyfin
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.image-pull-policy: Always
        kompose.service.expose: jellyfin.gruzin.eu
        kompose.service.expose.ingress-class-name: traefik
        kompose.service.expose.tls-secret: jellyfin-tls
        kompose.version: 1.38.0 (HEAD)
        kompose.volume.type: hostPath
        kuma.jellyfin.http.accepted_statuscodes: '["200-299", "302"]'
        kuma.jellyfin.http.name: Jellyfin Media Server
        kuma.jellyfin.http.url: https://jellyfin.gruzin.eu
      labels:
        io.kompose.service: jellyfin
    spec:
      containers:
        - image: jellyfin/jellyfin
          imagePullPolicy: Always
          name: jellyfin
          ports:
            - containerPort: 8096
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 2Gi
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
          volumeMounts:
            - mountPath: /config
              name: jellyfin-hostpath0
            - mountPath: /cache
              name: jellyfin-hostpath1
            - mountPath: /tv
              name: jellyfin-hostpath2
            - mountPath: /movies
              name: jellyfin-hostpath3
            - mountPath: /usr/local/share/fonts/custom
              name: jellyfin-hostpath4
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/hdd/media/jellyfin/config
          name: jellyfin-hostpath0
        - hostPath:
            path: /mnt/hdd/media/jellyfin/cache
          name: jellyfin-hostpath1
        - hostPath:
            path: /mnt/hdd/media/tvseries
          name: jellyfin-hostpath2
        - hostPath:
            path: /mnt/hdd/media/movies
          name: jellyfin-hostpath3
        - hostPath:
            path: /mnt/hdd/media/jellyfin/fonts
          name: jellyfin-hostpath4
