apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: jellyseerr.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: jellyseerr-tls
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.jellyseerr.http.accepted_statuscodes: '["200-299", "307"]'
    kuma.jellyseerr.http.name: Jellyseerr
    kuma.jellyseerr.http.url: https://jellyseerr.gruzin.eu
  labels:
    io.kompose.service: jellyseerr
  name: jellyseerr
spec:
  ingressClassName: traefik
  rules:
    - host: jellyseerr.gruzin.eu
      http:
        paths:
          - backend:
              service:
                name: jellyseerr
                port:
                  number: 5055
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - jellyseerr.gruzin.eu
      secretName: jellyseerr-tls
