apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: jellyseerr.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: jellyseerr-tls
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.jellyseerr.http.accepted_statuscodes: '["200-299", "307"]'
    kuma.jellyseerr.http.name: Jellyseerr
    kuma.jellyseerr.http.url: https://jellyseerr.gruzin.eu
  labels:
    io.kompose.service: jellyseerr
  name: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jellyseerr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.image-pull-policy: Always
        kompose.service.expose: jellyseerr.gruzin.eu
        kompose.service.expose.ingress-class-name: traefik
        kompose.service.expose.tls-secret: jellyseerr-tls
        kompose.version: 1.38.0 (HEAD)
        kompose.volume.type: hostPath
        kuma.jellyseerr.http.accepted_statuscodes: '["200-299", "307"]'
        kuma.jellyseerr.http.name: Jellyseerr
        kuma.jellyseerr.http.url: https://jellyseerr.gruzin.eu
      labels:
        io.kompose.service: jellyseerr
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: debug
            - name: PORT
              value: "5055"
            - name: TZ
              value: Europe/Warsaw
          image: ghcr.io/fallenbagel/jellyseerr:latest
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
          name: jellyseerr
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 5055
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: jellyseerr-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/hdd/opt/jellyseerrconfig
          name: jellyseerr-hostpath0
