apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: prowlarr.bay.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: prowlarr-tls
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.prowlarr.http.accepted_statuscodes: '["200-299"]'
    kuma.prowlarr.http.name: Prowlarr Indexer
    kuma.prowlarr.http.url: https://prowlarr.bay.gruzin.eu
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.image-pull-policy: Always
        kompose.service.expose: prowlarr.bay.gruzin.eu
        kompose.service.expose.ingress-class-name: traefik
        kompose.service.expose.tls-secret: prowlarr-tls
        kompose.version: 1.38.0 (HEAD)
        kompose.volume.type: hostPath
        kuma.prowlarr.http.accepted_statuscodes: '["200-299"]'
        kuma.prowlarr.http.name: Prowlarr Indexer
        kuma.prowlarr.http.url: https://prowlarr.bay.gruzin.eu
      labels:
        io.kompose.service: prowlarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Warsaw
          image: lscr.io/linuxserver/prowlarr:latest
          imagePullPolicy: Always
          name: prowlarr
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 9696
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: prowlarr-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/hdd/media/prowlarr/config
          name: prowlarr-hostpath0
