apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: prowlarr.bay.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: prowlarr-tls
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.prowlarr.http.accepted_statuscodes: '["200-299"]'
    kuma.prowlarr.http.name: Prowlarr Indexer
    kuma.prowlarr.http.url: https://prowlarr.bay.gruzin.eu
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
spec:
  ingressClassName: traefik
  rules:
    - host: prowlarr.bay.gruzin.eu
      http:
        paths:
          - backend:
              service:
                name: prowlarr
                port:
                  number: 9696
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - prowlarr.bay.gruzin.eu
      secretName: prowlarr-tls
