apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: qbittorrent.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: qbittorrent-tls
    kompose.service.type: LoadBalancer
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.qbittorrent.http.accepted_statuscodes: '["200-299"]'
    kuma.qbittorrent.http.name: qBittorrent
    kuma.qbittorrent.http.url: https://qbittorrent.gruzin.eu
  labels:
    io.kompose.service: qbittorrent
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.image-pull-policy: Always
        kompose.service.expose: qbittorrent.gruzin.eu
        kompose.service.expose.ingress-class-name: traefik
        kompose.service.expose.tls-secret: qbittorrent-tls
        kompose.service.type: LoadBalancer
        kompose.version: 1.38.0 (HEAD)
        kompose.volume.type: hostPath
        kuma.qbittorrent.http.accepted_statuscodes: '["200-299"]'
        kuma.qbittorrent.http.name: qBittorrent
        kuma.qbittorrent.http.url: https://qbittorrent.gruzin.eu
      labels:
        io.kompose.service: qbittorrent
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TORRENTING_PORT
              value: "6881"
            - name: TZ
              value: Europe/Warsaw
            - name: WEBUI_PORT
              value: "8080"
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          name: qbittorrent
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 1Gi
          ports:
            - containerPort: 6881
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-hostpath0
            - mountPath: /media
              name: qbittorrent-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/hdd/opt/qbittorrent
          name: qbittorrent-hostpath0
        - hostPath:
            path: /mnt/hdd/media
          name: qbittorrent-hostpath1
