apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: radarr.bay.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: radarr-tls
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.radarr.http.accepted_statuscodes: '["200-299"]'
    kuma.radarr.http.name: Radarr Movies
    kuma.radarr.http.url: https://radarr.bay.gruzin.eu
  labels:
    io.kompose.service: radarr
  name: radarr
spec:
  ingressClassName: traefik
  rules:
    - host: radarr.bay.gruzin.eu
      http:
        paths:
          - backend:
              service:
                name: radarr
                port:
                  number: 7878
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - radarr.bay.gruzin.eu
      secretName: radarr-tls
