apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: sonarr.bay.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: sonarr-tls
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.sonarr.http.accepted_statuscodes: '["200-299"]'
    kuma.sonarr.http.name: Sonarr TV
    kuma.sonarr.http.url: https://sonarr.bay.gruzin.eu
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  ingressClassName: traefik
  rules:
    - host: sonarr.bay.gruzin.eu
      http:
        paths:
          - backend:
              service:
                name: sonarr
                port:
                  number: 8989
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - sonarr.bay.gruzin.eu
      secretName: sonarr-tls
