apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: Always
    kompose.service.expose: sonarr.bay.gruzin.eu
    kompose.service.expose.ingress-class-name: traefik
    kompose.service.expose.tls-secret: sonarr-tls
    kompose.version: 1.38.0 (HEAD)
    kompose.volume.type: hostPath
    kuma.sonarr.http.accepted_statuscodes: '["200-299"]'
    kuma.sonarr.http.name: Sonarr TV
    kuma.sonarr.http.url: https://sonarr.bay.gruzin.eu
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.image-pull-policy: Always
        kompose.service.expose: sonarr.bay.gruzin.eu
        kompose.service.expose.ingress-class-name: traefik
        kompose.service.expose.tls-secret: sonarr-tls
        kompose.version: 1.38.0 (HEAD)
        kompose.volume.type: hostPath
        kuma.sonarr.http.accepted_statuscodes: '["200-299"]'
        kuma.sonarr.http.name: Sonarr TV
        kuma.sonarr.http.url: https://sonarr.bay.gruzin.eu
      labels:
        io.kompose.service: sonarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Warsaw
          image: lscr.io/linuxserver/sonarr:latest
          imagePullPolicy: Always
          name: sonarr
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8989
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: sonarr-hostpath0
            - mountPath: /tv
              name: sonarr-hostpath1
            - mountPath: /media/downloads
              name: sonarr-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/hdd/media/sonarr/data
          name: sonarr-hostpath0
        - hostPath:
            path: /mnt/hdd/media/tvseries
          name: sonarr-hostpath1
        - hostPath:
            path: /mnt/hdd/media/downloads
          name: sonarr-hostpath2
